CONFIG_VERSION: "0.1.2"  # DO NOT CHANGE

# Pixels can be entered in format number-only or number + suffix "px", for example - 2560px or 2560 or 2560 px

# GENERAL SETTINGS
HOST_SETTINGS:
  # Specify your screen resolution to ensure precise coordinate conversion from the Telegram window to your screen.
  # Example for a 2k monitor (resolution 2560x1440) - WIDTH: 2560px, HEIGHT: 1440px
  HOST_SCREEN_RESOLUTION:
    WIDTH: 2560
    HEIGHT: 1440

# IN-GAME SETTINGS
BLUM_SETTINGS:
  # Specify the name of the application window where you will run Telegram with the Blum bot.
  # This should be the exact name as it appears in your system's window manager.
  # For example, if the window title is "Telegram - Blum Bot", use that exact string.
  # This ensures the AI clicker targets the correct window for object detection (stars, bombs, freeze).
  TELEGRAM_WINDOW_NAME: "Blum"

  # The clicker includes a system to avoid clicking on a bomb if it is too close to a star.
  # Due to the delay between object appearance and detection, a bomb might occasionally be clicked by mistake.
  # To mitigate this, a coefficient is used to extend the safe distance between bombs and stars.
  # The value represents the multiplier for the distance, measured in star widths.
  # For example, a value of 1.5 means a star will not be clicked if a bomb is closer than 1.5 star widths.
  # Recommended value: 1.5-2. Adjust according to your system's performance and in-game results.
  STARS_FROM_BOMB: 1.5

  # Specify the padding from the edges of your screen where clicks should not occur.
  # This is useful to prevent the AI clicker from clicking on system UI elements like the toolbar or edges of the screen.
  # Each value represents the padding in pixels.
  NON_CLICKABLE_AREA:
    PADDING_LEFT: 200
    PADDING_RIGHT: 200
    PADDING_TOP: 50
    PADDING_BOTTOM: 50
